### ISSUE TITLE
#1 Agregar descripción del proyecto en el readme.

### ISSUE THREAD

**Issue by dcastaneda** [dcastaneda/ludajaro#1]
Cada integrante debe contribuir a la
 descripción del proyecto.
@lumaacevedo
@javiro76
@DavidRestrepo81
@rodrihurt

**Comment by lumaacevedo** [comment]
La idea principal es contruir una pagina web en donde se encuentre la información de la empresa, la forma de contacto y posiblemente un carrito de compras con sus productos mas importantes.

**Comment by DavidRestrepo81** [comment]
En la pagina Web hacer la descripcion de cada producto, su valor al por mayor y al detal, costo del domicilio para asi brindar un excelente servicio para los clientes.

**Comment by rodrihurt** [comment]
Para lograrlo creamos un grupo de trabajo donde cada uno de los participantes ha asumido un rol que se rota a lo largo del proyecto con el fin de tener una visión completa del desarrollo web.
